app:
  build: .
  volumes:
   - "$PWD/logs:/opt/tomcat/logs"
  ports:
   - "8080:8080"
  links:
   - elasticsearch:elasticsearch
elasticsearch:
  image: elasticsearch
  volumes:
   - "$PWD/es/config:/usr/share/elasticsearch/config"
  ports:
   - "9200:9200"
   - "9300:9300"